name: Deployment
run-name: ${{ github.actor }} deployment 🚀
on:
  push:
    branches: 
      - master
  pull_request:
    branches: [ master ]
jobs:
  init:
    strategy:
      matrix:
        node-version: [ 18.x, 17.x ]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**package-lock.json') }}
      - name: install modules 
        run: npm ci
      - name: build project
        run: npm run build
  testing:
    strategy:
      matrix:
        node-version: [ 18.x, 17.x ]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs: init
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**package-lock.json') }}
      - name: install modules 
        run: npm ci
      - name: format
        run: npm run format
      - name: lint
        run: npm run lint
      - name: test lint
        run: npm run test:lint
  build:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: build
          name: build-files
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build project
        uses: actions/download-artifact@v3
        with:
          name: build-files
  print:
    runs-on: ubuntu-latest
    needs: [init, testing, build, deploy]
    steps:
      - name: Succesful print
        run: echo All jobs will be completed success! 